create table if not exists profession (
    id integer generated by default as identity primary key,
    title varchar(100) not null,
    description text not null
);

create table if not exists department (
    id integer generated by default as identity primary key,
    title varchar(100) not null,
    additional_info text not null,
    parent_department_id integer references department (id) on delete cascade
);

create table if not exists employee (
    id integer generated by default as identity primary key,
    full_name varchar(100) not null,
    additional_info varchar(100) not null,
    profession_id integer references profession (id) on delete set null,
    department_id integer references department (id) on delete set null
);